"""
Graph Constants
"""

from __future__ import annotations

# Node Types
PERSON_NODE = "PERSON"
LOCATION_NODE = "LOCATION"
ORGANIZATION_NODE = "ORGANIZATION"
PLATFORM_NODE = "PLATFORM"
DRUG_NODE = "DRUG"
PAYMENT_NODE = "PAYMENT"

# Relationship Types
MENTIONS = "MENTIONS"
LOCATED_IN = "LOCATED_IN"
USES = "USES"
ASSOCIATED_WITH = "ASSOCIATED_WITH"
TRANSACTS_WITH = "TRANSACTS_WITH"
